export const NEW_TASK = "task/newTask"
export const DELETE_TASK = "task/deleteTask"
export const MODIFY_TASK = "task/modifyTask"
export const LOAD_TASKS = "task/loadTasks"
export const LOAD_COURSES = "course/loadCourses"